apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: logger-server
  labels:
    app: logger-server
spec:
  selector:
    matchLabels:
      app: logger-server
  replicas: 3 # tells deployment to run 3 pods matching the template
  template:
    metadata:
      labels:
        app: logger-server
        version: v2
    spec:
      containers:
      - name: logger-server
        image: hdwinkel/logger-server-jvm-arm64:v2
        env:
        - name: QUARKUS_DATASOURCE_URL
          value: "jdbc:mysql://192.168.188.40:3306/logger"
        ports:
        - containerPort: 8080

