version: '3.3'
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'logger'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'logger'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'data!logger'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'data!root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - /mnt/docker/mariadb:/var/lib/mysql


