apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: logger-deployment
spec:
  selector:
    matchLabels:
      app: logger
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: logger
    spec:
      containers:
      - name: logger-server-jvm-arm64
        image: hdwinkel/logger-server-jvm-arm64:v1
        env:
        - name: QUARKUS_DATASOURCE_URL
          value: "jdbc:mysql://192.168.10.130:3306/logger"
        ports:
        - containerPort: 8080

